accounts/urls.py
from django.conf.urls import url
from .views import *

app_name = 'accounts'

urlpatterns = [
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_view, name='home'),
    url(r'^post/', include('post.urls')),
    url(r'^accounts/', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import *

app_name = 'post'

urlpatterns = [
    url(r'^index/', post_index, name='index'),
    url(r'^create/', post_create, name='create'),
    url(r'^detail/(?P<slug>[\w-]+)/', post_detail, name='detail'),
    url(r'^update/(?P<slug>[\w-]+)/', post_update, name='update'),
    url(r'^delete/(?P<slug>[\w-]+)/', post_delete, name='delete'),
]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse

def home_view(request):
    if request.user.is_authenticated():
        name = request.user.first_name
        fullname = request.user.get_full_name()
        context = {
            'name' : fullname
        }
    else:
        context = {
            'name': 'Misafir'
        }

    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %}Django Tutorial{% endblock %}</title>  <!-- Django Tutorial default title olarak ayarlandı -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

</head>
<body>
    {% include 'header.html' %}


    <div class="container-fluid" style="margin-top: 60px;">
    {% include "messages.html" %}
        {% block body %}



        {% endblock %}
    </div>

    <br><br><br>
    <H3>Footer</H3>

    <script src="{% static 'js/jquery-min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-warning">
      <a class="navbar-brand" href="{% url 'home' %}">Django Dersleri</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post:index' %}">Posts</a>
          </li>
          {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'post:create' %}">Create Post</a>
              </li>
          {% endif %}
        </ul>
          {% if not request.user.is_authenticated %}
              <a class="btn btn-success" href="{% url 'accounts:login' %}">Giris Yap</a>
              <a class="btn btn-primary" style="margin-left: 5px; margin-right: 5px;" href="{% url 'accounts:register' %}">Kayit Ol</a>
        {% endif %}
            {% if request.user.is_authenticated %}
              <a class="btn btn-danger" style="margin-left: 5px; margin-right: 5px;" href="{% url 'accounts:logout' %}">Cikis</a>
        {% endif %}
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'post:index' %}">
          <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Ara</button>
        </form>
      </div>
    </nav>
</div>

templates/home.html
{% extends 'base.html' %}

{% block title %}

    Ana Sayfa - {{ block.super }}

{% endblock %}


{% block body %}

    <p>Merhaba, burası ana sayfa ! {{ name }}</p>

{% endblock %}

templates/messages.html
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}